attributes:
  emc_username:
    value: "username"
    label: "EMC VNX username"
    description: "EMC VNX username."
    weight: 75
    type: "text"
    regex:
      source: '\S'
      error: "Username field cannot be empty"
  emc_password:
    value: "password"
    label: "EMC VNX password"
    description: "EMC VNX password."
    weight: 80
    type: "password"
    regex:
      source: '\S'
      error: "Password field cannot be empty"
  emc_sp_a_ip:
    value: ""
    label: "EMC VNX SP A IP"
    description: "EMC VNX Service Processor A IP address."
    weight: 90
    type: "text"
    regex:
      source: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
      error: "Specify valid IPv4 address"
  emc_sp_b_ip:
    value: ""
    label: "EMC VNX SP B IP"
    description: "EMC VNX Service Processor B IP address."
    weight: 90
    type: "text"
    regex:
      source: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
      error: "Specify valid IPv4 address"
  emc_pool_name:
    value: ""
    label: "EMC VNX pool name"
    description: "EMC VNX pool name (optional)"
    weight: 95
    type: "text"
